# User: postgres
# Pass: postgrespassword
---
version: '3.1'

services:

  postgres:
    image: postgres:14
    restart: always
    env_file: .env
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./entrypoint-initdb.d:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file: .env
    environment:
      # Required to work with Codespaces reverse proxy
      # Ref: https://github.com/community/community/discussions/17918
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: 1
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: 1
    ports:
      - "5050:80"
